#!/bin/sh

IP="$(echo $SSH_CONNECTION | cut -d " " -f 1)"
HOSTNAME=$(hostname)
NOW=$(date +"%Y-%m-%d %H:%M:%S")

CONTENT="New login, From IP: $IP , HostName: $HOSTNAME , Logged time: $NOW"

RES=$(curl -X POST \
  -F "chat_id=111111111" \
  -F "text=${CONTENT}" \
  -o /dev/null --silent \
  -w %{http_code} \
  "https://api.telegram.org/xxxxxxxx")
